import streamlit as st
import datetime
import uuid
import time
import os
import cv2
import tempfile
from PIL import Image
from ultralytics import YOLO
from utils.db import get_connection
from utils.s3_upload import upload_to_s3
from utils.email_alert import send_email_alert
from utils.system_alerts import create_alert
from utils.ui_components import app_footer

st.title("👥 Crowd Density Monitoring")

# LOAD MODEL
@st.cache_resource
def load_model():
    return YOLO("models/crowd_best.pt")

model = load_model()

# INPUT SECTION 
st.subheader("📍 Location Details")

city = st.text_input("City", placeholder="Eg : Chennai")
location = st.text_input("Location / Area", placeholder="Eg : Anna Nagar")

col1, col2 = st.columns(2)
with col1:
    latitude = st.number_input("Latitude", format="%.6f")
with col2:
    longitude = st.number_input("Longitude", format="%.6f")

event_type = st.selectbox(
    "Event Type",
    ["Normal", "Festival", "Protest", "Concert", "Sports Event", "Public Gathering"]
)

crowd_file = st.file_uploader(
    "Upload Crowd Image / Video",
    type=["jpg", "png", "mp4"]
)

# DENSITY FUNCTION 
def density_level(count):
    if count < 20:
        return "low"
    elif count < 50:
        return "medium"
    elif count < 100:
        return "high"
    else:
        return "extreme"

# RUN BUTTON 
if st.button("🚀 Run Crowd Analysis"):

    if crowd_file is None or location == "":
        st.warning("Please provide location and media file")
        st.stop()

    crowd_id = str(uuid.uuid1())

    person_count = 0
    max_conf = 0

    # IMAGE 
    if crowd_file.type.startswith("image"):

        image = Image.open(crowd_file)
        results = model(image, conf=0.25)

        plotted = results[0].plot()
        st.image(plotted, use_container_width=True)

        boxes = results[0].boxes

        if boxes is not None:
            person_count = len(boxes)
            max_conf = float(boxes.conf.max())

        temp_path = f"temp_{time.time()}.jpg"
        image.save(temp_path)

    # VIDEO
    else:

        suffix = os.path.splitext(crowd_file.name)[1]

        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            tmp.write(crowd_file.read())
            temp_path = tmp.name

        cap = cv2.VideoCapture(temp_path)

        frame_skip = 5

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            if int(cap.get(1)) % frame_skip != 0:
                continue

            results = model(frame, conf=0.01)

            boxes = results[0].boxes

            if boxes is not None:
                person_count += len(boxes)
                if boxes.conf.numel() > 0:
                    max_conf = max(max_conf, float(boxes.conf.max()))

        cap.release()
        st.video(temp_path)

    density = density_level(person_count)

    # S3 UPLOAD
    s3_key = f"crowd/{city}_{int(time.time())}_{crowd_file.name}"
    image_url = upload_to_s3(temp_path, s3_key)

    # SAVE TO RDS 
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        INSERT INTO crowd_density_data (
            crowd_id, image_url, timestamp,
            city, location, latitude, longitude,
            estimated_count, density_level,
            event_type, model_confidence
        )
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """, (
        crowd_id,
        image_url,
        datetime.datetime.now(),
        city,
        location,
        latitude,
        longitude,
        person_count,
        density,
        event_type,
        max_conf
    ))

    conn.commit()
    conn.close()

    # EMAIL ALERT 
    if density in ["high", "extreme"]:

        send_email_alert(
            subject="🚨 Smart City Alert: High Crowd Density Detected 🆘",
            message=f"""
Smart City Crowd Monitoring System

A HIGH crowd density situation has been detected.

Location:
City: {city}
Area: {location}
Coordinates: {latitude}, {longitude}

Crowd Details:
People Count: {person_count}
Density Level: {density.upper()}
Event Type: {event_type}
Confidence Score: {max_conf:.2f}
Time: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

Recommended Action:
Deploy crowd control measures and ensure public safety.

This is an automated alert generated by the Smart City AI Platform.
"""
        )

        create_alert(
            alert_type="crowd",
            location=f"{city} - {location} ({latitude}, {longitude})",
            severity="high" if density == "extreme" else "medium",
            message=f"{density.capitalize()} crowd detected with {person_count} people",
            email_sent=True
        )

    # PROFESSIONAL OUTPUT 
    if density == "extreme":
        st.error(
            f"Extreme crowd density detected with approximately {person_count} people. "
            f"Emergency crowd control measures have been triggered."
        )

    elif density == "high":
        st.warning(
            f"High crowd density detected with approximately {person_count} people. "
            f"Authorities have been notified for immediate action."
        )

    elif density == "medium":
        st.info(
            f"Moderate crowd density observed with {person_count} people. "
            f"Situation is under monitoring."
        )

    else:
        st.success(
            "Crowd levels are within safe limits. No immediate action required."
        )

    os.remove(temp_path)



app_footer()